### ISSUE TITLE
internal server error with proof

### ISSUE THREAD

**Issue by ganeshbista209** [Itzdvbravo/BravoClan#13]
when i do clan info
it says internal server error please fix it
![Screenshot_2020-07-13-23-21-16-012_com android chrome](https://user-images.githubusercontent.com/66917109/87336661-d4254a00-c55f-11ea-8295-8e850007794d.jpg)
![Uploading Screenshot_2020-07-13-23-21-09-785_com.android.chrome.jpg…]()

**Comment by Itzdvbravo** [comment]
Uh you only sended me the trace backs, send the error which would be above it.
