### ISSUE TITLE
[Suggestion] Boosters

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [Itzdvbravo/BravoClan#23]
Ass boosters(boost clan xp per kill) into the game where players can either...
A. Buy boosters for x amount of time(You'll have to intergrate EconomyAPI and/or MultiEconomy)
B. Have a permission for an unlimited time that'll give you a booster(Ex. bc.boost.x)
C. My personal favorite, both
x=number

**Comment by Itzdvbravo** [comment]
Ok
