### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Johnsonk79** [Itzdvbravo/BravoClan#4]
Hi! Thanks for the plugin, its awesome, but it would be even better in my opinion if we can set a floating text leaderboard of the top clans, thanks!

**Comment by Itzdvbravo** [comment]
That's the work of another plugin, tho!

**Comment by Johnsonk79** [comment]
Yea I agree but it would be awesome if it can be included in this plugin :D, if not feel free to close this issue

**Comment by Itzdvbravo** [comment]
I would think about it, thank you for your contribution.
