### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by ZEHNNNN** [Itzdvbravo/BravoClan#6]
Can You Add Multiworld Support ?

**Comment by Itzdvbravo** [comment]
What's the point of multi-world support here?

**Comment by ZEHNNNN** [comment]
in clan cant pvp so in skywar also can pvp too i want you to make it multiworld support

**Comment by Itzdvbravo** [comment]
Ah i see i see, will add it np.

**Comment by Itzdvbravo** [comment]
Done.

**Comment by ZEHNNNN** [comment]
rate time <3
