### ISSUE TITLE
plugin errors

### ISSUE THREAD

**Issue by fakol** [Itzdvbravo/BravoClan#9]
Here is the plugin error 
![Screenshot_20200614-185522](https://user-images.githubusercontent.com/41354153/84596771-acfc2f80-ae70-11ea-80ed-c0a001051c38.png)
And the error link works for me, which may be wrong I don’t know

**Comment by Itzdvbravo** [comment]
Aight thx fixed soon

**Comment by Itzdvbravo** [comment]
Uh.. i don't get the error message i checked the codes, don't see that error tho..., reinstall the plugin and see

**Comment by fakol** [comment]
> Новое обновление исправляет все проблемы, вы можете перезапустить сервер один или два раза, и он больше не будет отображаться.

Good

**Comment by fakol** [comment]
> The new update fixes em all no worries, you can restart the server once or twice and it won't show it again.

Good

**Comment by fakol** [comment]
When entering the command /clan top throws from the server,Please correct

**Comment by Itzdvbravo** [comment]
Sir, i don't get this error tho?

**Comment by fakol** [comment]
> Sir, i don't get this error tho?

do you understand Russian ? I can write in Russian to make it easier for you if you know this language

**Comment by Itzdvbravo** [comment]
I am comfortable with english, it's your device, it'll be fixed when the new update gets accepted.
Some devices, it's case-sensitive for some not, for me, it's not, so that's the problem.

**Comment by fakol** [comment]
Can you create another plugin for removing items from the creative? It’s just that I kind of know how to write a bit of plugins too, but I didn’t succeed here

**Comment by Itzdvbravo** [comment]
Doesn't meet the requirements for making an plugin, will think later on future
